translateapp/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
        path('dashboard', views.dashboard, name="dashboard"),
        path('profile/<int:user_id>', views.profile, name="profile"),
        path('register', views.register, name="register"),
]

translateapp/app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
        path('jobs', views.jobs_index, name="jobs"),
        path('jobs/new', views.new_job, name="new_job"),
        path('jobs/<int:job_id>', views.job_detail, name="job_detail"),
        path('jobs/<int:job_id>/bid', views.bid, name="bid"),
        path('bids/<int:bid_id>/accept', views.accept_bid, name="accept_bid"),
        path('bids/<int:bid_id>/deliver', views.deliver_translation, name="deliver_translation"),
        path('bids/<int:bid_id>', views.bid_detail, name="bid_detail"),
        path('bids/<int:bid_id>/rating', views.rate_bid, name="rate_bid"),
        path('bids/<int:bid_id>/dispute', views.raise_dispute, name="dispute"),
		path('jobs/<int:job_id>/message',  views.send_message, name="message"),
]

translateapp/translateapp/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

translateapp/accounts/models.py
from django.db import models

# Create your models here.

translateapp/app/models.py
from django.db import models

from django.contrib.auth.models import User

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    translator = models.BooleanField()
    def __str__(self):
        return f"{self.id} - {self.name}"

    def rating(self):
        ratings = Rating.objects.filter(rated=self.user)
        if ratings.count() == 0:
            return "No ratings yet"
        else:
            score = [ rating.rating for rating in ratings ]
            return sum(score) / len(score)

    def raise_if_invalid_balance(self):
        if self.balance < 0:
            raise ValueError("Balance cannot be negative")

class Job(models.Model):
    class Status(models.TextChoices):
        AVAILABLE = 'available', "Available"
        ASSIGNED = 'assigned', "Assigned"
        IN_PROGRESS = 'in_progress', "In Progress"
        COMPLETED = 'completed', "Completed"

    class Field(models.TextChoices):
        ART = 'art', "Art"
        BUS = 'business', "Business"
        COMP = 'computers', "Computers"
        EDU = 'education', "Education"
        ENG = 'engineering', "Engineering"
        FIN = 'finance', "Finance"
        LAW = 'law', "Law"
        LIT = 'literature', "Literature"
        MED = 'medicine', "Medicine"
        SCI = 'science', "Science"
        SOC = 'social_sciences', "Social Sciences"
        TECH = 'technology', "Technology"

    class Language(models.TextChoices):
        ENG = 'en', "English"
        SPA = 'spa', "Spanish"
        FRE = 'fr', "French"
        GER = 'de', "German"
        ITA = 'it', "Italian"
        JPN = 'ja', "Japanese"
        CRO = 'hr', "Croatian"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    source_lang = models.CharField(
            max_length=3, 
            choices=Language.choices,
            default=Language.ENG,
    )
    target_lang = models.CharField(
            max_length=3,
            choices=Language.choices,
            default=Language.CRO,
    )
    field = models.CharField(
            max_length=100,
            choices=Field.choices,
            default=Field.ENG,
    )
    budget = models.DecimalField(max_digits=8, decimal_places=2)
    text = models.TextField()
    status = models.CharField(
            max_length=100, 
            choices=Status.choices,
            default=Status.AVAILABLE,
    )
    translation = models.TextField(blank=True, null=True)
    def __str__(self):
        return f"{self.user.account.name} - {self.title}"

    def accepted_bid(self):
        return self.bid_set.filter(accepted=True).first()

    def accepted_bidder(self):
        return self.accepted_bid().bidder.account

    def owner(self):
        return self.user.account

    # Helper method to check if the job is available, since checking the status
    # directly from the template is not very readable.
    def is_available(self):
        return self.status == self.Status.AVAILABLE

    def is_completed(self):
        return self.status == self.Status.COMPLETED

    @classmethod
    def accepted_jobs_for(cls, user):
        # Svi bidovi gdje je user napravio job na koji je biddano
        accepted_bids = Bid.objects.filter(job__in=user.job_set.all(), accepted=True)
        # Svi jobovi gdje je user napravio job i bidano je na job 
        accepted_jobs = [ bid.job for bid in accepted_bids if bid.job.status != "completed" ]
        return accepted_jobs

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    accepted = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.bidder.account.name} - {self.job.title} - {self.price}"
    def job_owner(self):
        return self.job.user

class Dispute(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    bid = models.OneToOneField(Bid, on_delete=models.CASCADE)
    reason = models.TextField(blank=False, null=False)

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    text = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.sender.account.name} - {self.receiver.account.name} - {self.text[:20]}"

class Rating(models.Model):
    rater = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rater')
    rated = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rated')
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    bid = models.OneToOneField(Bid, on_delete=models.CASCADE)
    rating = models.IntegerField()

translateapp/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from app.models import Account, Job, Bid, Dispute, Message, Rating
from app.forms import UserForm, AccountForm


# Create your views here.

# See the comment in forms.py for an explanation of why we use two forms
def register(request):
    if request.method == 'POST':
        # Each form is validated separately, each form takes the data from the
        # request that is relevant to it.
        user_form = UserForm(request.POST)
        account_form = AccountForm(request.POST)
        # Only if both forms are valid, we save the data to the database
        if user_form.is_valid() and account_form.is_valid():
            user = user_form.save()
            # We need to set the password separately, because the UserForm
            # doesn't have a password field, it uses two fields for the password
            # and password confirmation.
            user.set_password(user_form.cleaned_data['password1'])
            user.save()

            # We need to set the user field on the account before we can save it
            account = account_form.save(commit=False)
            account.user = user
            account.save()
            return HttpResponseRedirect(reverse('accounts:dashboard'))
        else:
            return render(request, 'accounts/register.html', {'user_form': user_form, 'account_form': account_form})
    else:
        user_form = UserForm()
        account_form = AccountForm()
        return render(request, 'accounts/register.html', {'user_form': user_form, 'account_form': account_form})

@login_required
def dashboard(request):
    user = request.user
    my_jobs = user.job_set.all()
    my_messages = Message.objects.filter(receiver=user) | Message.objects.filter(sender=user)
    my_messages = my_messages.order_by('-sent_at')
    my_bids = user.bid_set.all()
    my_won_bids = user.bid_set.filter(accepted=True)
    context = {
        'my_jobs': my_jobs,
        'my_messages': my_messages,
        'my_bids': my_bids,
        'my_won_bids': my_won_bids,
    }

    return render(request, 'accounts/dashboard.html', context)


def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    accepted_jobs = Job.accepted_jobs_for(user)
    completed_jobs = Job.objects.filter(user=user, status='completed')

    bids = user.bid_set.all()
    won = user.bid_set.filter(accepted=True)

    context = {
        'profile_user': user,
        'accepted_jobs': accepted_jobs,
        'completed_jobs': completed_jobs,
        'bids': bids,
        'won': won,
    }
    return render(request, 'accounts/profile.html', context)

translateapp/accounts/templates/accounts/dashboard.html
{% extends 'app/base.html' %}

<!--USER DASHBOARD-->

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Hello {{ user.account.name }}</h1>
      {% if user.account.translator %}
        <h2>Translator - Rating: {{ user.account.rating }}</h2>
      {% endif %}
      <p>Token balance: <strong>{{ user.account.balance }}</strong></p>
      <p>Email: {{ user.email }}</p>

      <h1>My Jobs</h1>

      {% for job in my_jobs  %}

        <div class="job">
          <h3>{{ job.title }}</h3>
          <p>
            <strong>{{ job.description   }}</strong> </br>
            Source language: {{ job.source_lang   }}; 
            Target language: {{ job.target_lang   }}
          </p>
          <p>{{ job.field   }}</p>
          <p>{{ job.budget   }}</p>
          <p>{{ job.status   }}</p>

          <div>
          {% for bid in job.bid_set.all  %}
            <div class="bid {% if bid.accepted %} accepted {% endif %}">
              <h3>
                Bidder: 
                <a href="{% url 'accounts:profile' bid.bidder.id %}">
                  {{ bid.bidder.account.name }}
                </a>
              </h3>
              <p>
                <strong>Price: {{ bid.price }}</strong>, 
                Accepted: {{ bid.accepted }}
              </p>
              {% if not bid.accepted and job.is_available %}
                <!--check models.py for the is_available method-->
                <p>
                  <form action="{% url 'app:accept_bid' bid.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Accept bid">
                  </form>
                </p>
              {% elif bid.completed %}
                <p>
                  {% if bid.rating %} You rated it {{ bid.rating.rating }} {% endif %}
                  <a href="{% url 'app:bid_detail' bid.id %}">See the completed translation</a>
                </p>
              {% endif %}
            </div>
          {% endfor %}
          </div>

          </div>
      {% endfor %}

      {% if user.account.translator %}
      <h1>My translations dashboard</h1>

      <h2>My bids</h2>
        {% for bid in my_bids  %}
          <div class="bid {% if bid.accepted %} accepted {% endif %}">
            <p>
              <strong>My bid on {{ bid.job.title }} for {{ bid.price }} tokens.</strong>
            </p>
            <p>
              {{ bid.job.description   }}</br>
              From {{ bid.job.get_source_lang_display }} to {{ bid.job.get_target_lang_display }}.
            </p>
            <p>Field: {{ bid.job.get_field_display }}; Status:  {{ bid.job.status   }}</p>
          </div>
        {% endfor %}

      <h2>My won bids (Jobs assigned to me)</h2>
        {% for bid in my_won_bids  %}
          {% if not bid.completed %}
            <div class="bid {% if bid.accepted %} accepted {% endif %}">
              <p>
                <strong>My bid on {{ bid.job.title }} for {{ bid.price }} tokens.</strong>
              </p>
              <p>
                {{ bid.job.description   }}</br>
                From {{ bid.job.get_source_lang_display }} to {{ bid.job.get_target_lang_display }}.
              </p>
              <p>Field: {{ bid.job.get_field_display }}; Status:  {{ bid.job.status   }}</p>

              <p><a href="{% url 'app:deliver_translation' bid.id %}">Submit your translation</a></p>
            </div>
          {% endif %}
        {% endfor %}

      <h2>My completed jobs</h2>
        {% for bid in my_won_bids  %}
          {% if bid.completed %}
            <div class="bid {% if bid.accepted %} accepted {% endif %}">
              <p>
                <strong>My bid on {{ bid.job.title }} for {{ bid.price }} tokens.</strong>
              </p>
              <p>
                {{ bid.job.description   }}</br>
                From {{ bid.job.get_source_lang_display }} to {{ bid.job.get_target_lang_display }}.
              </p>
              <p>Field: {{ bid.job.get_field_display }}; Status:  {{ bid.job.status   }}</p>
                <p>
                  <a href="{% url 'app:bid_detail' bid.id %}">See the completed translation</a>
                </p>
            </div>
          {% endif %}
        {% endfor %}


      {% endif %}
    </div>
    <div class="col-md-3">
      <h1>Messages</h1>
      <div class="messages">
        {% for message in my_messages %}
          <div class="message {% if user == message.sender %} my-message {% else %} their-message {% endif %}">
            {% if user != message.sender  %}
              <strong> From: 
                <a href="{% url 'accounts:profile' message.sender.id %}">
                  {{ message.sender.account.name }}
                </a>
              </strong> </br>
            {% endif %}
            <small>{{ message.sent_at }}</small>
            <p>{{ message.text }}</p>
          </div>
        {% endfor %}


      </div>
    </div>
    
  </div>
  
</div>

{% endblock content %}

translateapp/accounts/templates/accounts/profile.html
{% extends 'app/base.html' %}

<!--USER PROFILE -->

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>{{ profile_user.account.name }}'s profile page</h1>
      {% if user.account.translator %}
        <h2>Translator - Rating: {{ profile_user.account.rating }}</h2>
      {% endif %}
      <p>Email: {{ profile_user.email }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>User's accepted jobs</h1>
      {% for job in accepted_jobs  %}

        <div class="job">
          <h3>{{ job.title }}</h3>
          <p>
            <strong>{{ job.description   }}</strong> </br>
            Source language: {{ job.source_lang   }}; 
            Target language: {{ job.target_lang   }}
          </p>
          <p>{{ job.field   }}</p>
          <p>{{ job.budget   }}</p>
          <p>{{ job.status   }}</p>

          <p>
            <strong>
              {{ job.accepted_bidder.name }} was accepted for this job with the 
              bid of {{ job.accepted_bid.price }}
            </strong>
          </p>

        </div>
      {% empty %}
        <p>No accepted jobs</p>
      {% endfor %}

    </div>
    <div class="col-md-12">
      <h1>User's completed jobs</h1>
      {% for job in completed_jobs  %}

        <div class="job">
          <h3>{{ job.title }}</h3>
          <p>
            <strong>{{ job.description   }}</strong> </br>
            Source language: {{ job.source_lang   }}; 
            Target language: {{ job.target_lang   }}
          </p>
          <p>{{ job.field   }}</p>
          <p>{{ job.budget   }}</p>
          <p>{{ job.status   }}</p>

          <p>
            <strong>
              {{ job.accepted_bidder.name }} has completed this job for the 
              price of {{ job.accepted_bid.price }}
            </strong>
          </p>

        </div>
      {% empty %}
        <p>No completed jobs</p>
      {% endfor %}

    </div>
    {% if user.account.translator %}
      <div class="col-md-12">
        <h1>Translator's stats</h1>
        <h2>User's bids</h2>
        {% for bid in bids  %}
          <h3>Bid on {{ bid.job.title }} for {{ bid.price }} tokens</h3>
          {% if bid.accepted %}
            <p class="won-job">Won the job!</p>
          {% else %}
            <p class="lost-job">Someone else was cheaper :(</p>
          {% endif %}

        {% empty %}
          <p>No bids on any jobs</p>
        {% endfor %}

        <h2>Won jobs - currently working on:</h2>
        {% for bid in won  %}
          <h3>{{ bid.job.title }} for {{ bid.price }} tokens</h3>
          <p>Translating from 
            {{ bid.job.get_source_lang_display }} to 
            {{ bid.job.get_target_lang_display }} a text 
            in the field of {{ bid.job.get_field_display }}.
          </p>
          <p>Job posted by <a href="{% url "accounts:profile" bid.job.user.id %}">{{ bid.job.user.account.name }}</a></p>

        {% empty %}
          <p>Didn't win any jobs!</p>
        {% endfor %}



      </div>
    {% endif %}
  </div>
  
</div>

{% endblock content %}

translateapp/accounts/templates/accounts/register.html
{% extends 'app/base.html' %}

{% load widget_tweaks %}

{% block content %}
  <h1>Register an account with us!</h1>
  <form method="post">
    {% csrf_token %}

    {% for hidden in user_form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {% for hidden in account_form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2>Enter you user details</h2>
          {% for field in user_form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:'form-control' }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          {% endfor %}

          <h2>Enter you account details</h2>
          {% for field in account_form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:'form-control' }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
          {% endfor %}

          <div class="form-group">
            <button type="submit" class="btn btn-success">
              <span class="glyphicon glyphicon-ok"></span> Save
            </button>
            <a href="{% url 'home_path' %}" class="btn btn-default">Cancel</a>
          </div>
        </div>
      </div>
    </div>
    

  </form>
{% endblock %}